// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujodxlzlfvdwqufkgdnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqb2R4bHpsZnZkd3F1ZmtnZG53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMzE4MTQsImV4cCI6MjA3MzgwNzgxNH0.lACzxZrVOLEf996sq6oLV5M48k174JGWrsXkvbrWsEM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Custom storage adapter with fallback for PWA persistence
const persistentStorage = {
  getItem: (key: string): string | null => {
    try {
      const localValue = localStorage.getItem(key);
      if (localValue) return localValue;
      // Fallback to sessionStorage if localStorage fails
      return sessionStorage.getItem(key);
    } catch {
      return sessionStorage.getItem(key);
    }
  },
  setItem: (key: string, value: string): void => {
    try {
      localStorage.setItem(key, value);
      // Also backup to sessionStorage for PWA recovery
      sessionStorage.setItem(key, value);
    } catch {
      sessionStorage.setItem(key, value);
    }
  },
  removeItem: (key: string): void => {
    try {
      localStorage.removeItem(key);
      sessionStorage.removeItem(key);
    } catch {
      sessionStorage.removeItem(key);
    }
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: persistentStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});